## Fichier : docker-compose.yml
version: '3'
services:
  cv:
    container_name: anto-card
    build: .
    ports:
      - "3000:3000"
    # stdin_open: true
    volumes:
       - .:/usr/src/app/card-profile-antony
       - /usr/src/app/card-profile-antony/node_modules
    tty: true
  # nginx:
  #   build : ./nginx
  #   ports: 80:80
         